import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { FirebaseAuthProvider } from "./context/FirebaseAuthContext";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <FirebaseAuthProvider>
          <body className={inter.className}>
            <main>{children}</main>
          </body>
        </FirebaseAuthProvider>
      </ClerkProvider>
    </html>
  );
}
